apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-go-uzqdawmi
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/rhtap_qe/backend-tests-go-uzqdawmi:5214d77b40fc45b460e3a6c56a88950d1080b0b0@sha256:5e5a34e5efe5e54f4ac9933c02c95d914234164e2b14c6cd905b023decc299e8
          name: container-image
